### ISSUE TITLE
Question：网页版

### ISSUE THREAD

**Issue by laylalaisy** [msdx/rank-github-china#1]
想请问一下为什么不采用web端呢？

**Comment by msdx** [comment]
本来想写小程序的，但是我不会啊。

**Comment by laylalaisy** [comment]
@msdx 因为我第一反应是 很想看一下 然后看到要下载app就不太想看了2333 感觉如果能够增加一个web版本的话更好啦~

**Comment by msdx** [comment]
那我学习一下小程序去

**Comment by msdx** [comment]
小程序里面不能直接请求 github 的 api。配置了自己的域名之后，又得是 https 的。

**Comment by dwqs** [comment]
@laylalaisy @msdx  小程序上查看：https://github.com/msdx/rank-github-china/issues/2 :blush::blush::blush:

**Comment by msdx** [comment]
@dwqs 机智。
